### ISSUE TITLE
Support for the "transform" attribute in common tags.

### ISSUE THREAD

**Issue by adario** [pocketsvg/PocketSVG#175]
Hello,

I'm attaching a patch against the current master (as of this writing) that adds support for the "transform" attribute in basic tags, e.g. rect, circle, ellipse and line.  This has been tested on macOS 10.15.2 and iOS 13.3.

Should you decide to accept the patch, similar support would be useful for the path and polygon tags.

Thanks,
Dario

[transform_attribute.diff.zip](https://github.com/pocketsvg/PocketSVG/files/4021336/transform_attribute.diff.zip)

**Comment by arielelkin** [comment]
Hi Dario! 

Thank you very much for your patch. Could you please submit it as a [pull request](https://github.com/pocketsvg/PocketSVG/pulls) so that we can review it?

**Comment by adario** [comment]
Hi Ariel,

I'd love to, but I don't have write access to the repo, so I can't push my feature/transform_attribute branch — where else could I submit the PR from?

Thanks,
D.

**Comment by arielelkin** [comment]
You don't actually need to have write access to the repo in order to submit a PR, all you need to do is

1. fork the [pocketsvg repo](https://github.com/pocketsvg/PocketSVG/issues/175) (click on the Fork button in the top right)
1. clone your fork locally
1. apply your patch to your local fork
1. commit and push
1. open a pull request from your fork into the pocketsvg repo. 

See: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

let me know if you get stuck 🙂

**Comment by arielelkin** [comment]
closed via https://github.com/pocketsvg/PocketSVG/pull/176

**Comment by adario** [comment]
I've created https://github.com/pocketsvg/PocketSVG/pull/176
