### ISSUE TITLE
Implement support for named colors

### ISSUE THREAD

**Issue by gordondove** [pocketsvg/PocketSVG#60]
I tried to load an svn with a 'black' stroke.  The SVGEngine tries to interpret this as a triplet, and asserts.

According to section 11.2 of SVG1.1, colour names are valid.

The error is around SVGEngine:287.

'none' looks to be handled correctly, but not named colours.

[Broken.svg.zip](https://github.com/pocketsvg/PocketSVG/files/531241/Broken.svg.zip)

I'm raising this for your edification, so priority is very low, and I'll be happy with a won't fix. Since I'm only looking for the path, I'll just preprocess my svgs to strip out the colours.

**Comment by kyouko-taiga** [comment]
I'll add that a similar issue happens when the property is a resource identifier (i.e. `url(...)`), which also be a valid value according to SVG1.1.

Looking at the code, it seems like only `none` and `#xxxxxx` can be properly parsed (see [SVGEngine.mm:282-287](https://github.com/pocketsvg/PocketSVG/blob/master/SVGEngine.mm#L282-L287) and [SVGEngine.mm:563-564](https://github.com/pocketsvg/PocketSVG/blob/master/SVGEngine.mm#L563-L564)).

**Comment by fjolnir** [comment]
@gordondove I don't have any objection to adding named color support, as long as it's nice and compact. But I don't desire it enough to implement it myself.

@kyouko-taiga Resource loading is firmly out of the scope of PocketSVG :)
