### ISSUE TITLE
Unresolved identifier 'SVGLayer'

### ISSUE THREAD

**Issue by black-lotus** [pocketsvg/PocketSVG#84]
Hi,

I got error when using SVGLayer

`SVGLayer(svgSource: svgString)`

> Use of unresolved identifier 'SVGLayer'

Thank you in advance

**Comment by arielelkin** [comment]
Hi @black-lotus 

See if you can solve your issue by looking at https://github.com/pocketsvg/PocketSVG/issues/80

If that doesn't help, please let me have more details in order to help you out: 

* Are you opening the xcode project or the xcode workspace? 
* Are you trying to import the classes into a Swift or an ObjC file? 
* What specific error message are you seeing? 

Cheers

**Comment by black-lotus** [comment]
Hallo @arielelkin 

- Yes, i open with the xcode workspace
- I am trying to import PocketSVG `import PocketSVG` 
- I got this error `Use of unresolved identifier 'SVGLayer'`

I update cocoapods minimum platform to 9.0

`platform :ios, '9.0'`

but still i got same error

Regards

**Comment by arielelkin** [comment]
Then the problem is in how you've installed PocketSVG via Cocoapods. 

Try to see if you can solve your issue by following the advice here: https://guides.cocoapods.org/using/troubleshooting.html

If that doesn't help, create a github repository and push a project that reproduces the issue there. pass me the link and I'll take a look

**Comment by AbsolutRenal** [comment]
I think you are trying to use PocketSVG in a Swift project.
If so, you need to create a bridging header file to import Objective-C files, and specify this file under 'Objective-C Bridging Header' of the Build Settings

**Comment by coulCod** [comment]
I am also faced with this issue. And yes, I am use PocketSVG in a Swift project. Please, guide me how to add Objective-C Bridging Header to my project.

**Comment by coulCod** [comment]
In my case issue was because I do not specify PocketSVG version in my Pod file. The correct pod line must be pod 'PocketSVG', '~> 2.2.1'

**Comment by arielelkin** [comment]
This is often due to the `use_frameworks!` declaration missing from your Podfile. Your Podfile should look like this:

```
target 'TestProject' do
  use_frameworks!

  pod 'PocketSVG'

end
```

Let me know if this doesn't work.

**Comment by arielelkin** [comment]
inactivity; closing.
