### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by ldiqual** [pocketsvg/PocketSVG#88]
@arielelkin I see minor version bumps in cocoapods but I couldn't find a changelog or release notes on github. It would be great to have a changelog that keeps track of all changes to figure out whether upgrading is safe. http://keepachangelog.com/en/0.3.0/

**Comment by arielelkin** [comment]
@ldiqual we strictly follow [Semantic Versioning](http://semver.org/), so 

MAJOR versions indicate incompatible API changes,
MINOR versions indicate when we add functionality in a backwards-compatible manner, and
PATCH versions when we make backwards-compatible bug fixes.

We don't tag a commit otherwise. The version number therefore gives you sufficient information to know whether upgrading is safe. 

That aside, and given our `git log` is kept free of noise, I think that a changelog is a nice-to-have, but I don't consider it necessary at this stage. 

We should be adding release notes to MAJOR versions, however, as it facilitates people's decision over whether or not to upgrade. Let's keep that in mind, @fjolnir

**Comment by ldiqual** [comment]
@arielelkin Got it, thanks for the clarification. What is the recommended way to know what is in a release? For instance, I'm way more likely to upgrade PocketSVG if I know that a new release fixed a bug I was experiencing, but if I have no way to know the diff it'll be really hard to blindly semver (we hard pin library versions). Don't get me wrong, the answer could be as simple as looking into `git log`, but I believe users of your library needs to know what's going into their app and not just blindly trust semver.

**Comment by arielelkin** [comment]
If you're upgrading minor versions, the recommended way to know what's in a release is to check the `git log`. If you're upgrading major versions, the recommended way to know is checking the release notes, which we'll add to the forthcoming major version. 

In general, it's good practice for you to hard pin MAJOR versions, like this:

The semver contract ensures that any `pod update` you make doesn't break your builds, as you'll only be pulling backwards-compatible updates.
