### ISSUE TITLE
Is the drawing result GPU hardware accelerated?

### ISSUE THREAD

**Issue by trusktr** [pocketsvg/PocketSVG#94]
?

**Comment by SuperWomble** [comment]
ICoreGraphics is used for path creation and fundamental drawing operations. That's done mostly on the CPU. Things like shadows are going to hurt your performance, so try to do your image-building asynchronously. What happens after you build the image depends on how you create and manage the image. e.g. if you render in to a bitmap context, then the bitmap can be thrown around by the GPU at low cost. So, minimise rendering, and reuse the result as much as you can.

**Comment by fjolnir** [comment]
If you use the provided svgview/layer, then the drawing is done by a cashapelayer which renders on the gpu and is pretty fast.

**Comment by trusktr** [comment]
Thanks for the reply guys. I am looking for libraries that can create the graphics (the "fundamental drawing operations") entirely on the GPU as much as possible (tessalating paths, circles, etc).

A few so far:

- MonkVG paired with MonkSVG
- Pixi.js paired with pixi-svg
- Two.js

**Comment by SuperWomble** [comment]
@fjolnir Judging from the name of the CALayer subclass, it would seem that way, but according to WWDC 2014 session 221, only the composited drawing (i.e. the bitmap) is done on the GPU. Here are my notes from that session:

- CAShapeLayer first rasterizes the shape layer  on the CPU
- the rasterized layer is sent to the render server (for later compositing)
- this process can be expensive in CPU time
- to mitigate the cost, try using more CAShapeLayers, but each with less complexity. i.e. try composing shapes out of simpler shapes, and stack the CAShapeLayers behind each other in the same place in the view hierarchy. (They will be composited together).
- be very cautious about frequent changes to CAShapeLayers, because of cost; every time the shape layer changes, it has to be re-reasterized and re-sent over to the render server

@trusktr It sounds like you need a real-time vector solution, like OpenVG. If you need this for a 60fps game or Flash-like animation, then the basic Core Graphics + Core Animation model probably won't fit your needs. The model _is_ very fast, particularly once things are rendered, but it's not very suitable for dynamically changing vectors.

Unfortunately, OpenVG support on iOS is very spotty. It doesn't seem to have caught on as an API.

In any case, I would prototype using Core Graphics + Core Animation first, and profile it: see if it can do what you need to. You may be surprised. And remember that although some of the libraries you mention will do GPU-based shape rendering, there's also significant cost in terms of setup (e.g. javascript contexts).

**Comment by fjolnir** [comment]
I would suggest just testing CAShapeLayer, and seeing if the performance is good enough.

I don't know the implementation details of it, but it is obviously not just doing simple rasterization on the cpu, because if it were, then using it would be as  slow as just using CoreGraphics. I also don't know how it would do morphing between paths as smoothly as it does, if it were all on the cpu.

**Comment by SuperWomble** [comment]
Yeah, I'm also puzzled. The WWDC talk was pretty emphatic about the whole CPU thing, but that doesn't really seem to gel with the idea of a _Shape_ layer to me. Also, it contradicts other statements Apple have made about some path drawing happening on the GPU. e.g. setting properties on a CGLayer causes GPU drawing to occur, not bitmap rasterisation in the first instance.

**Comment by trusktr** [comment]
@SuperWomble The Unity SVG importer looks nice, but seems to be a one-time import, not for modifying an SVG document on each frame.

Good idea guys, I should just get a prototype running, even if with normal CPU rasterization, then see what my bottle neck is for specific applications.

One thing though, is that I want to make CG art just for fun, and I like the SVG API because it is so portable if rendered in the web, and just a nice 2D API conceptually. At the moment, I don't know how many things I will animate at once, but the upper limit could easily be thousands.

I've tried D3.hs force graphs with hundreds of nodes, and rendering with native SVG (the browser's) was just so slow. Moving to Pixi.js was much faster.

In general, I am working on a 3D library at http://GitHub.com/trusktr/infamous, so I don't have any specific application planned, I just am looking to have a super easy to use 2D API that I can use inside 3D scenes, and if the API could be SVG, I think you to would be amazing!

F.e., imagine making animated 2D characters by manipulating an SVG tree, then moving those characters around in 3D, all in a single WebGL context.

Or imagine a 3D game that a computer inside the game, and the UI on that in-game computer is done with SVG (including animations).

Coding that with SVG would just be so easy, conceptually, but in practice, the browser's (my preferred environment) SVG rendering is too slooooow, and copying a browser-native SVG texture from a canvas (the only way to do it with native browser APIs) makes it even slooooower.

So my goal is to be able to write SVG graphics and dynamically animate SVG scenes, frame by frame, with speed.

This would be an amazing environment to write graphical applications in.

Think "Three.js with an accelerated SVG renderer", except that I am making my own lib (not using Three.js, and wishing to have accelerated SVG rendering).

I am interested in writingy own 3D rendering stuff, but for SVG I think Two.js currently gets closest in practice, and I am also considering making a JS port of MonkVG but that would take more time. I will compare them to see what the conceptual differences are.

So that's my actual goal, and I am comparing also non-web libraries (like PocketSVG and others) to see what techniques they use under the hood, but ultimately I want the solution to be a web-based solution.

As for what I will make, I don't know yet! I have multiple ideas floating in my head, but I just want to have a path that will allow me to do most, and currently it seems like using Two.js for SVG rendering will be the way to go as native is so slow, then I'll make some concepts, then later I'll evaluate MonkVG to see what it does and if it can either be ported or ideas brought into Two.js.

For starters, up next next I am making an observer implementation to observe changes to an off-screen non-rendered SVG DOM, then I will be able to map those observations to changes on a Two.js WebGL scene graph.

That's basically it, thought I'd share what I'm actually trying to do. :]

**Comment by trusktr** [comment]
Example API usage I am aiming for is something like the following (note that my `<motor-node>` and `<motor-scene>` elements already exist for defining 3D scene graphs, can render basic WebGL meshes, and are animatable just like animating any other HTML elements in the web):

```js
document.body.innerHTML = `
<motor-scene webgl="true">
  <motor-node rotation="0 0 30" id="svgNode">
    <svg>
      ... SVG markup in here ...
    </svg>
  </motor-node>
</motor-scene>
`

// get the node
const svgNode = document.getElementById('svgNode')

// rotate the SVG graphic in 3D webgl space!
Motor.addRenderTask(time => {
  svgNode.rotation.y = 30 * Math.sin(time * 0.01)
})
```

I have prototypes of this already running with native SVG and Pixi.js, they render to a texture that is placed onto a Quad mesh. So the motor-scene with the svgNode id will automatically contain a Quad in this case, but it can come rain other meshes too (leaving that out of this example as not related to SVG, but in the future think animated SVG mappable onto any mesh...).

Motor-nodes are nestable, just like `<g>`roups in SVG, but with 3D transforms instead of 2D.

Currently, my prototypes just make a texture once, then they sit in the GPU, which is just like the CALayers approach, but I'm using vanilla WebGL to make my layers.

Next I will add the observation implementation to listen to the SVG DOM for changes and dynamically update Two.js/Pixi.js renderings. It already works with native SVG since the browser does it, and I can grab that texture through a canvas, but it is slooooooooow.

**Comment by trusktr** [comment]
Oops, "come rain" -> "contain"

**Comment by fjolnir** [comment]
You know that this is a library written in Objective-C right? It would be quite a lot of work to get it running in a browser.

If you do, and are considering some sort of native plugin architecture, you could also just use pocketsvg to parse the file, and then draw manually via a shader.

**Comment by trusktr** [comment]
@fjolnir 

> You know that this is a library written in Objective-C right? It would be quite a lot of work to get it running in a browser.

Yep yep, this is why I mentioned 

> I am comparing also non-web libraries (like PocketSVG and others) to see what techniques they use under the hood, but ultimately I want the solution to be a web-based solution.

**Comment by fjolnir** [comment]
Ah, sorry. I didn't read carefully enough.
